name: Build and smoke test docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # PostgreSQL service container
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: notimon_test
          POSTGRES_PASSWORD: notimon_test
          POSTGRES_DB: notimon_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
            push: false
            load: true
            tags: notimon:latest
            cache-from: type=gha
            cache-to: type=gha,mode=max

      - name: Start container
        run: |
          docker run \
              --detach \
              --name notimon \
              --network container:postgres \
              -e DATABASE_URL=postgresql://notimon_test:notimon_test@localhost:5432/notimon_test \
              --log-driver local \
              --health-cmd "curl -f http://localhost:3000 || exit 1" \
              --health-interval 5s \
              --health-timeout 3s \
              --health-retries 5 \
              notimon:latest

          # Wait for container to be healthy
          timeout 60s bash -c 'while [[ "$(docker inspect -f {{.State.Health.Status}} notimon)" != "healthy" ]]; do sleep 2; done'

          # Show logs for debugging
          docker logs notimon


      - run: docker logs notimon
        if: always()
