name: Build and smoke test docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # Install jq for JSON parsing
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # Generate VAPID keys and export as environment variables
      - name: Generate VAPID keys
        id: vapid
        run: |
          VAPID_JSON=$(web-push generate-vapid-keys --json)
          echo "VAPID_PUBLIC_KEY=$(echo $VAPID_JSON | jq -r .publicKey)" >> $GITHUB_ENV
          echo "VAPID_PRIVATE_KEY=$(echo $VAPID_JSON | jq -r .privateKey)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build \
            --build-arg VAPID_PUBLIC_KEY=$VAPID_PUBLIC_KEY \
            --build-arg VAPID_PRIVATE_KEY=$VAPID_PRIVATE_KEY \
            --build-arg VAPID_CONTACT=mailto:notimon@example.com \
            -t notimon:latest .

      - name: Start container
        run: |
          docker run \
              --name notimon \
              -e DATABASE_URL=postgresql://nonsense:nonsense@localhost:5432/notimon_test \
              notimon:latest 2>&1 \
            | grep "Can't reach database server at"

      - run: docker logs notimon
        if: always()
