name: Build and smoke test docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
            push: false
            load: true
            tags: notimon:latest
            cache-from: type=gha
            cache-to: type=gha,mode=max

      - name: Start container
        run: |
          docker run \
              --name notimon \
              -e DATABASE_URL=postgresql://nonsense:nonsense@localhost:5432/notimon_test \
              notimon:latest 2>&1 \
            | grep "Can't reach database server at"

      - run: docker logs notimon
        if: always()
