name: Unit and integration test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # PostgreSQL service container
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: notimon_test
          POSTGRES_PASSWORD: notimon_test
          POSTGRES_DB: notimon_test
        ports:
          - 5432:5432
        # Health check to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npm run prisma:generate

      - name: Run database migrations
        run: npm run prisma:migrate:test

      - name: Run tests
        run: npm test
